version: '3'
services:
  hydra:
    build: .
    ports:
      - "80:3000"
    volumes:
      - ./chrome_profiles:/app/chrome_profiles
      - ./logs:/app/logs
    environment:
      - VITE_API_URL=http://144.126.225.177
      - DISPLAY=:99
    restart: unless-stopped
    command: sh -c "npm run build && npm run preview"