version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./chrome_profiles:/app/chrome_profiles
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: unless-stopped
    command: npm run preview